package com.example.ocean.model;

// Generated 13-May-2014 16:13:57 by Hibernate Tools 3.4.0.CR1

/**
 * Certificate generated by hbm2java
 */
public class Certificate implements java.io.Serializable {

	private Integer idcertificate;
	private User user;
	private Keyring keyring;
	private byte[] data;

	public Certificate() {
	}

	public Certificate(User user, Keyring keyring, byte[] data) {
		this.user = user;
		this.keyring = keyring;
		this.data = data;
	}

	public Integer getIdcertificate() {
		return this.idcertificate;
	}

	public void setIdcertificate(Integer idcertificate) {
		this.idcertificate = idcertificate;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Keyring getKeyring() {
		return this.keyring;
	}

	public void setKeyring(Keyring keyring) {
		this.keyring = keyring;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

}
