package com.example.ocean.model;

// Generated 13-May-2014 16:13:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Keyring generated by hbm2java
 */
public class Keyring implements java.io.Serializable {

	private String serialnumber;
	private User user;
	private String publickey;
	private Set certificates = new HashSet(0);

	public Keyring() {
	}

	public Keyring(String serialnumber, User user, String publickey) {
		this.serialnumber = serialnumber;
		this.user = user;
		this.publickey = publickey;
	}

	public Keyring(String serialnumber, User user, String publickey,
			Set certificates) {
		this.serialnumber = serialnumber;
		this.user = user;
		this.publickey = publickey;
		this.certificates = certificates;
	}

	public String getSerialnumber() {
		return this.serialnumber;
	}

	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPublickey() {
		return this.publickey;
	}

	public void setPublickey(String publickey) {
		this.publickey = publickey;
	}

	public Set getCertificates() {
		return this.certificates;
	}

	public void setCertificates(Set certificates) {
		this.certificates = certificates;
	}

}
